from jupyter_deploy import constants, verify_utils
from jupyter_deploy.engine.engine_config import EngineConfigHandler
from jupyter_deploy.engine.engine_outputs import EngineOutputsHandler
from jupyter_deploy.engine.enum import EngineType
from jupyter_deploy.engine.supervised_execution import CompletionContext, DisplayManager
from jupyter_deploy.engine.terraform import tf_config, tf_outputs
from jupyter_deploy.engine.vardefs import TemplateVariableDefinition
from jupyter_deploy.enum import SecretSource, StoreType
from jupyter_deploy.exceptions import InvalidPresetError, SecretNotFoundError
from jupyter_deploy.handlers.base_project_handler import BaseProjectHandler, write_store_config
from jupyter_deploy.manifest import JupyterDeploySecretV1
from jupyter_deploy.provider.manifest_command_runner import ManifestCommandRunner
from jupyter_deploy.provider.resolved_clidefs import ResolvedCliParameter, StrResolvedCliParameter
from jupyter_deploy.provider.store.store_manager import StoreInfo
from jupyter_deploy.provider.store.store_manager_factory import StoreManagerFactory


class ConfigHandler(BaseProjectHandler):
    _handler: EngineConfigHandler

    def __init__(self, display_manager: DisplayManager, output_filename: str | None = None) -> None:
        """Base class to manage the configuration of a jupyter-deploy project."""
        super().__init__(display_manager=display_manager)
        self.preset_name: str | None = None

        if self.engine == EngineType.TERRAFORM:
            self._handler = tf_config.TerraformConfigHandler(
                project_path=self.project_path,
                project_manifest=self.project_manifest,
                command_history_handler=self.command_history_handler,
                output_filename=output_filename,
                display_manager=display_manager,
            )
        else:
            raise NotImplementedError(f"ConfigHandler implementation not found for engine: {self.engine}")

    def _create_outputs_handler(self) -> EngineOutputsHandler:
        """Create an engine-specific outputs handler."""
        if self.engine == EngineType.TERRAFORM:
            return tf_outputs.TerraformOutputsHandler(
                project_path=self.project_path,
                project_manifest=self.project_manifest,
            )
        raise NotImplementedError(f"Outputs handler not available for engine: {self.engine}")

    def has_recorded_variables(self) -> bool:
        """Return True if the file generated by jd config to record variable values exists."""
        return self._handler.has_recorded_variables()

    def verify_preset_exists(self, preset_name: str) -> bool:
        """Return True if the requested preset is defined by this template."""
        return self._handler.verify_preset_exists(preset_name)

    def list_presets(self) -> list[str]:
        """Return the list of default presets that this template supports."""
        return self._handler.list_presets()

    def validate_preset(self, preset_name: str) -> None:
        """Validate that the preset exists, raise InvalidPresetError if not.

        Raises:
            InvalidPresetError: If the preset is not valid for this template.
        """
        if not self.verify_preset_exists(preset_name):
            valid_presets = self.list_presets()
            raise InvalidPresetError(preset_name, valid_presets)

    def set_preset(self, preset_name: str | None) -> None:
        """Set the preset name to use for configuration."""
        self.preset_name = preset_name

    def verify_requirements(self) -> None:
        """Verify that all required tools are installed.

        Raises:
            ToolRequiredError: If a required tool is not installed or has an incorrect version.
        """
        requirements = self.project_manifest.get_requirements()
        verify_utils.verify_tools_installation(requirements)

    def has_used_preset(self, expected_preset_name: str | None) -> bool:
        """Return True if the handler has used the preset.

        Always return True if expected_preset argument is None.
        This method returns False when it detected recorded variables values that the users
        decided not to reset.
        """
        return expected_preset_name is None or expected_preset_name == self.preset_name

    def reset_recorded_variables(self) -> bool:
        """Delete the file in the project dir where the previous inputs were recorded.

        Returns:
            bool: True if files were deleted, False otherwise
        """
        return self._handler.reset_recorded_variables()

    def reset_recorded_secrets(self) -> bool:
        """Delete the file in the project dir where the secrets were recorded.

        Returns:
            bool: True if files were deleted, False otherwise
        """
        return self._handler.reset_recorded_secrets()

    def reset_store_id(self) -> None:
        """Clear the store-id from .jd/store.yaml, preserving store-type and project-id."""
        store_type = self.get_store_type_from_config_or_manifest()
        project_id = self.get_project_id_from_config()
        write_store_config(
            self.project_path,
            store_type=store_type.value if store_type else None,
            store_id=None,
            project_id=project_id,
        )

    def ensure_store(
        self,
        store_type: StoreType | None = None,
        store_id: str | None = None,
    ) -> StoreInfo | None:
        """Ensure the remote project store exists, creating it if necessary.

        Resolves store type and ID from CLI args > .jd/store.yaml > manifest.
        Persists resolved values to .jd/store.yaml so subsequent runs skip discovery.

        When store_id is set, verifies the store exists with find_store()
        and raises ProjectStoreNotFoundError if not found.

        Returns:
            StoreInfo if the store was ensured, None if project store is not configured.

        Raises:
            ProjectStoreNotFoundError: If store_id is set but the store does not exist.
        """
        # Resolve store type: CLI > config
        resolved_store_type = store_type if store_type is not None else self.get_store_type_from_config_or_manifest()

        if not resolved_store_type:
            self.display_manager.warning("No project store type configured. Skipping store setup.")
            return None

        # Resolve store id: CLI > config
        resolved_store_id = store_id if store_id else self.get_store_id_from_config()

        # Preserve existing project-id across config rewrites
        existing_project_id = self.get_project_id_from_config()

        # When store-id is set, verify the bucket exists rather than creating one
        if resolved_store_id is not None:
            store_manager = StoreManagerFactory.get_manager(store_type=resolved_store_type, store_id=resolved_store_id)
            store_info = store_manager.find_store()
            write_store_config(
                self.project_path,
                store_type=resolved_store_type,
                store_id=resolved_store_id,
                project_id=existing_project_id,
            )
            return store_info

        store_manager = StoreManagerFactory.get_manager(store_type=resolved_store_type, store_id=resolved_store_id)
        store_info = store_manager.ensure_store(self.display_manager)

        # Persist to .jd/store.yaml so subsequent runs skip discovery
        write_store_config(
            self.project_path,
            store_type=resolved_store_type,
            store_id=store_info.store_id,
            project_id=existing_project_id,
        )

        return store_info

    def configure(
        self, variable_overrides: dict[str, TemplateVariableDefinition] | None = None
    ) -> CompletionContext | None:
        """Set inputs of the project, calls the engine, return CompletionContext."""
        return self._handler.configure(preset_name=self.preset_name, variable_overrides=variable_overrides)

    def record(self) -> None:
        """Save the values of the variables and secrets to disk in the project dir."""
        self._handler.record()

    def mask_secrets(self) -> None:
        """Replace all sensitive variable values in variables.yaml with a mask."""
        self._handler.variables_handler.mask_secrets()

    def restore_secrets(
        self,
        restore_all: bool = False,
        restore_names: list[str] | None = None,
    ) -> None:
        """Fetch masked secret values from its store and write them to variables.yaml.

        Args:
            restore_all: If True, restore all masked sensitive variables.
            restore_names: If provided, restore only the named sensitive variables.

        Raises:
            SecretNotFoundError: If a secret cannot be restored.
        """
        if not restore_all and not restore_names:
            return

        variables_config = self._handler.variables_handler.variables_config
        masked_vars = {
            k: v
            for k, v in variables_config.required_sensitive.items()
            if v is None or v == constants.MASKED_SECRET_VALUE
        }

        if restore_names:
            # Validate all requested names exist in required_sensitive
            for name in restore_names:
                if name not in variables_config.required_sensitive:
                    raise SecretNotFoundError(name, "not a sensitive variable in this template")
            # Filter to only the requested names
            vars_to_restore = {k: v for k, v in masked_vars.items() if k in restore_names}
        else:
            vars_to_restore = masked_vars

        if not vars_to_restore:
            self.display_manager.warning("No masked secrets to restore.")
            return

        # Resolve command definition (raises CommandNotImplementedError if missing)
        cmd_def = self.project_manifest.get_command(constants.SECRET_REVEAL_COMMAND)

        # Create outputs handler to resolve output ARNs
        outputs_handler = self._create_outputs_handler()

        # Create command runner
        cmd_runner = ManifestCommandRunner(
            display_manager=self.display_manager,
            output_handler=outputs_handler,
            variable_handler=self._handler.variables_handler,
        )

        restored_values: dict[str, str] = {}

        for var_name in vars_to_restore:
            secret_def = self.project_manifest.get_secret(var_name)
            secret_id = self._resolve_secret_id(secret_def, outputs_handler)

            cli_params: dict[str, ResolvedCliParameter] = {
                constants.SECRET_REVEAL_CLI_PARAM: StrResolvedCliParameter(
                    parameter_name=constants.SECRET_REVEAL_CLI_PARAM,
                    value=secret_id,
                ),
            }

            self.display_manager.info(f"Restoring secret: {var_name}")
            cmd_runner.run_command_sequence(cmd_def, cli_params)
            secret_value = cmd_runner.get_result_value(cmd_def, constants.SECRET_REVEAL_RESULT_NAME, str)
            restored_values[var_name] = secret_value

        # Write all restored values to variables.yaml
        self._handler.variables_handler.sync_project_variables_config(restored_values)
        self.display_manager.success(f"Restored {len(restored_values)} secret(s).")

    @staticmethod
    def _resolve_secret_id(secret_def: JupyterDeploySecretV1, outputs_handler: EngineOutputsHandler) -> str:
        """Resolve the secret identifier (e.g. ARN) from the secret definition's source."""
        source_type = secret_def.get_source_type()

        if source_type == SecretSource.TEMPLATE_OUTPUT:
            outputs = outputs_handler.get_full_project_outputs()
            output_name = secret_def.source_key
            if output_name not in outputs:
                raise SecretNotFoundError(
                    secret_def.name,
                    f"output '{output_name}' not found (project may not be deployed yet)",
                )
            output_def = outputs[output_name]
            if not hasattr(output_def, "value") or output_def.value is None:
                raise SecretNotFoundError(
                    secret_def.name,
                    f"output '{output_name}' has no value",
                )
            return str(output_def.value)

        raise NotImplementedError(f"unsupported secret source: {source_type}")
