workspace_operator_namespace     = "jupyter-k8s-system"
workspace_router_namespace       = "jupyter-k8s-router"
workspace_shared_namespace       = "jupyter-k8s-shared"
workspace_operator_chart_oci     = "oci://ghcr.io/jupyter-infra/charts/jupyter-k8s"
workspace_operator_chart_version = "0.2.0"
workspace_router_chart_oci       = "oci://ghcr.io/jupyter-infra/charts/jupyter-k8s-aws-oidc"
workspace_router_chart_version   = "0.1.1"
traefik_crd_chart_version        = "1.15.0"
