FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

ARG SERVICE_GID
ARG DOCKER_GID
ARG SERVICE_UID

USER root

# 1/ Map docker group with specific GIDs
RUN groupadd -g ${DOCKER_GID} docker && \
    groupadd -g ${SERVICE_GID} jovyan

# 2/ Create a non-root user "jovyan" with a home dir
RUN useradd -m -s /bin/bash -u ${SERVICE_UID} -g ${SERVICE_GID} -G docker jovyan

# 3/ Install the docker CLI
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg

RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian bookworm stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 5/ create jupyter default config dirs
RUN mkdir -p /etc/jupyter
COPY jupyter_server_config.py /etc/jupyter/jupyter_server_config.py

# 4/ create a dir for UV, copy jupyter toml file, run uv
RUN mkdir -p /opt/uv/jupyter
COPY pyproject.jupyter.toml /opt/uv/jupyter/pyproject.toml
RUN uv sync --directory /opt/uv/jupyter

# 6/ Change dirs ownership
RUN chown -R jovyan:jovyan /opt/uv
RUN chown -R jovyan:jovyan /home/jovyan
RUN chown -R jovyan:jovyan /etc/jupyter

# 7/ Switch user and workdir
WORKDIR /home/jovyan
USER jovyan

ENTRYPOINT []
CMD ["uv", "run", "--directory", "/opt/uv/jupyter", "jupyter", "lab", \
     "--no-browser", \
     "--ip=0.0.0.0", \
     "--IdentityProvider.token=" ]