services:
  nginx:
    user: "${SERVICE_UID}:${SERVICE_GID}"
    image: nginxinc/nginx-unprivileged:latest
    ports:
      - "80:8080"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
  ngrok:
    user: "${SERVICE_UID}:${SERVICE_GID}"
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "nginx:8080"  # Point to the nginx service
      - "--domain"
      - "mastodon-closing-catfish.ngrok-free.app"
      - "--oauth"
      - "google"
      - "--oauth-allow-email"
      - "jonathan.guinegagne@gmail.com"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - web
    depends_on:
      - nginx  # Ensure nginx starts before ngrok
networks:
  web:
    driver: bridge